import numpy as np
from torch import nn
import torch
import pytorch_lightning as L
from torchvision import transforms
from torch.nn import functional as F
import timm
from plyfile import PlyData, PlyElement
import os
from core.gs_enderer import Renderer
class DinoWrapper(L.LightningModule):
    """
    Dino v1 wrapper using huggingface transformer implementation.
    """
    def __init__(self, model_name: str, is_train: bool = False):
        super().__init__()
        self.model, self.processor = self._build_dino(model_name)
        self.freeze(is_train)

    def forward(self, image):
        # image: [N, C, H, W], on cpu
        # RGB image with [0,1] scale and properly size
        # This resampling of positional embedding uses bicubic interpolation
        outputs = self.model.forward_features(self.processor(image))

        return outputs[:,1:]
    
    def freeze(self, is_train:bool = False):
        print(f"======== image encoder is_train: {is_train} ========")
        if is_train:
            self.model.train()
        else:
            self.model.eval()
        for name, param in self.model.named_parameters():
            param.requires_grad = is_train
    
    @staticmethod
    def _build_dino(model_name: str, proxy_error_retries: int = 3, proxy_error_cooldown: int = 5):
        import requests
        try:
            model = timm.create_model(model_name, pretrained=True, dynamic_img_size=True)
            data_config = timm.data.resolve_model_data_config(model)
            processor = transforms.Normalize(mean=data_config['mean'], std=data_config['std'])
            return model, processor
        except requests.exceptions.ProxyError as err:
            if proxy_error_retries > 0:
                print(f"Huggingface ProxyError: Retrying in {proxy_error_cooldown} seconds...")
                import time
                time.sleep(proxy_error_cooldown)
                return DinoWrapper._build_dino(model_name, proxy_error_retries - 1, proxy_error_cooldown)
            else:
                raise err
def inverse_sigmoid(x):
    return torch.log(x/(1-x))

def rsh_cart_3(xyz: torch.Tensor):
    """Computes all real spherical harmonics up to degree 3.

    This is an autogenerated method. See
    https://github.com/cheind/torch-spherical-harmonics
    for more information.

    Params:
        xyz: (N,...,3) tensor of points on the unit sphere

    Returns:
        rsh: (N,...,16) real spherical harmonics
            projections of input. Ynm is found at index
            `n*(n+1) + m`, with `0 <= n <= degree` and
            `-n <= m <= n`.
    """
    x = xyz[..., 0]
    y = xyz[..., 1]
    z = xyz[..., 2]

    x2 = x**2
    y2 = y**2
    z2 = z**2
    xy = x * y
    xz = x * z
    yz = y * z

    return torch.stack(
        [
            xyz.new_tensor(0.282094791773878).expand(xyz.shape[:-1]),
            -0.48860251190292 * y,
            0.48860251190292 * z,
            -0.48860251190292 * x,
            1.09254843059208 * xy,
            -1.09254843059208 * yz,
            0.94617469575756 * z2 - 0.31539156525252,
            -1.09254843059208 * xz,
            0.54627421529604 * x2 - 0.54627421529604 * y2,
            -0.590043589926644 * y * (3.0 * x2 - y2),
            2.89061144264055 * xy * z,
            0.304697199642977 * y * (1.5 - 7.5 * z2),
            1.24392110863372 * z * (1.5 * z2 - 0.5) - 0.497568443453487 * z,
            0.304697199642977 * x * (1.5 - 7.5 * z2),
            1.44530572132028 * z * (x2 - y2),
            -0.590043589926644 * x * (x2 - 3.0 * y2),
        ],
        -1,
    )   
        

class ResidualBlock(L.LightningModule):
    def __init__(self, in_channels, out_channels,stride, feat_vol, eps):
        super(ResidualBlock, self).__init__()
        
        self.conv1 = nn.Conv3d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
        self.relu = nn.LeakyReLU()
        self.conv2 = nn.Conv3d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False)
        self.relu2 = nn.LeakyReLU()
        self.shortcut = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv3d(in_channels, out_channels, kernel_size=1, stride=stride, bias=False),
                # nn.LayerNorm([out_channels,feat_vol,feat_vol,feat_vol],eps=eps),
                nn.LeakyReLU()
            )
        # self.conv3 = nn.Conv3d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False)
        self.conv3 = nn.Conv3d(out_channels, out_channels, kernel_size=1, stride=1,bias=False)
        self.bn3 = nn.LayerNorm([out_channels,feat_vol,feat_vol,feat_vol],eps=eps)
        self.relu3 = nn.LeakyReLU()


    def forward(self, x):
        residual = x
        ### main path
        out = self.conv1(x)
        out = self.relu(out)
        out = self.conv2(out)
        out = self.relu2(out)
        ### short path
        out += self.shortcut(residual)
        ###
        out = self.relu3(self.bn3(self.conv3(out)))
        
        return out
       
class GSF(L.LightningModule):
    def __init__(self, input_dim:int, inner_dim: int,
                 num_heads: int, eps: float,
                attn_drop: float = 0., attn_bias: bool = False,
                mlp_ratio: float = 2., mlp_drop: float = 0.,block_size: int = 2):
        super(GSF, self).__init__()
        self.cnn_img = nn.Sequential(
            ResidualBlock(input_dim,512,1,feat_vol=32,eps=1e-5),
            ResidualBlock(512,256,1,feat_vol=32,eps=1e-5),
            ResidualBlock(256,128,1,feat_vol=32,eps=1e-5),
            ResidualBlock(128,inner_dim,1,feat_vol=32,eps=1e-5),
            )
        self.cnn_nor = nn.Sequential(
            ResidualBlock(input_dim,512,1,feat_vol=32,eps=1e-5),
            ResidualBlock(512,256,1,feat_vol=32,eps=1e-5),
            ResidualBlock(256,128,1,feat_vol=32,eps=1e-5),
            ResidualBlock(128,inner_dim,1,feat_vol=32,eps=1e-5),
            )
        self.normal_img = nn.LayerNorm(inner_dim)
        self.normal_nor = nn.LayerNorm(inner_dim)
        self.normal_GF = nn.LayerNorm(inner_dim*2)
        self.G_cross_attn = nn.MultiheadAttention(
            embed_dim=inner_dim, num_heads=num_heads, kdim=inner_dim, vdim=inner_dim,
            dropout=attn_drop, bias=attn_bias, batch_first=True)
        self.S_cross_attn = nn.MultiheadAttention(
            embed_dim=inner_dim, num_heads=num_heads, kdim=inner_dim, vdim=inner_dim,
            dropout=attn_drop, bias=attn_bias, batch_first=True)
        self.GS_cross_attn = nn.MultiheadAttention(
            embed_dim=inner_dim*2, num_heads=num_heads, kdim=inner_dim*2, vdim=inner_dim*2,
            dropout=attn_drop, bias=attn_bias, batch_first=True)
        self.mlp = nn.Sequential(
            nn.Linear(inner_dim*2, int(inner_dim*2 * mlp_ratio)),
            nn.LeakyReLU(),
            nn.Dropout(mlp_drop),
            nn.Linear(int(inner_dim*2 * mlp_ratio), inner_dim),
            nn.Dropout(mlp_drop)
            
        )
        self.block_size = block_size
        self.init(self.mlp)
    def init(self, layers):
        # MLP initialization as in mipnerf360
        init_method = "xavier"
        if init_method:
            for layer in layers:
                if not isinstance(layer, nn.Linear):
                    continue 
                if init_method == "kaiming_uniform":
                    torch.nn.init.kaiming_uniform_(layer.weight.data)
                elif init_method == "xavier":
                    torch.nn.init.xavier_uniform_(layer.weight.data)
                torch.nn.init.zeros_(layer.bias.data)
        
    def get_patches(self,x,B,C,block_size,group_axis):
        patches = x.unfold(2, block_size, block_size).unfold(3, block_size, block_size).unfold(4, block_size, block_size)
        patches = patches.reshape(B, C, -1, block_size**3)
        patches = torch.einsum('bcgl->bglc',patches).reshape(B*group_axis**3, block_size**3,C)
        return patches
        
    def forward(self, img_i,nor_i):
        B,_,D,H,W = img_i.shape
        group_axis = int(D/self.block_size)
        img_i = self.cnn_img(img_i)
        nor_i = self.cnn_nor(nor_i)
        img_i_ps = self.get_patches(img_i,img_i.shape[0],img_i.shape[1],self.block_size,group_axis)
        nor_i_ps = self.get_patches(nor_i,nor_i.shape[0],nor_i.shape[1],self.block_size,group_axis)
        SF_feats_ps = img_i_ps + self.S_cross_attn(self.normal_img(img_i_ps),nor_i_ps,nor_i_ps, need_weights=False)[0]
        GF_feats_ps = nor_i_ps + self.G_cross_attn(self.normal_nor(nor_i_ps),img_i_ps,img_i_ps, need_weights=False)[0]
        GF_fusion = torch.concat((SF_feats_ps,GF_feats_ps),dim=2)
        GF_fusion = GF_fusion + self.GS_cross_attn(GF_fusion,GF_fusion,GF_fusion, need_weights=False)[0]
        C = GF_fusion.shape[-1]
        GF_fusion = GF_fusion.view(B, group_axis,group_axis,group_axis,self.block_size,self.block_size,self.block_size,C) 
        GF_fusion = torch.einsum('bdhwzyxc->bcdzhywx',GF_fusion).reshape(B,img_i.shape[1]+nor_i.shape[1],D,H,W).permute(0,2,3,4,1)
        GF_fusion = self.mlp(self.normal_GF(GF_fusion))
        return GF_fusion
        
        
        
        
        
class Network(L.LightningModule):
    def __init__(self, cfg):
        super(Network, self).__init__()
        self.feat_vol_reso = cfg.model.vol_feat_reso
        self.scene_size = cfg.model.scene_size
        self.view_color = cfg.view_color
        self.register_buffer("volume_grid", self.build_dense_grid(self.feat_vol_reso))
        self.img_encoder = DinoWrapper(
            model_name=cfg.model.encoder_backbone,
            is_train=False,
        ).cuda()
        self.move = cfg.move_range
        self.input_views = cfg.view
        encoder_feat_dim = self.img_encoder.model.num_features
        self.dir_norm_img = ModLN(encoder_feat_dim, 16*2, eps=1e-5).cuda()
        self.dir_norm_nor = ModLN(encoder_feat_dim, 16*2, eps=1e-5).cuda()
        input_dim = 768
        feat_dim = 32
        self.offset = cfg.model.per_voxel_gs
        # view embedding
        if cfg.model.view_embed_dim > 0:
            self.view_embed = nn.Parameter(torch.randn(1, self.input_views*2, cfg.model.view_embed_dim,1,1,1) * (1. / cfg.model.view_embed_dim) ** 0.5)
            self.view_embed_e = True
        self.mlp_dim = (cfg.sh_degree+1)**2*3+3+1+2+4
        self.GF_fusion = GSF(
            input_dim=input_dim+cfg.model.view_embed_dim,
            inner_dim=feat_dim, 
            num_heads=16, 
            eps=1e-6
        ).cuda()
        num_layer = 2
        layers_coarse = [nn.Linear(feat_dim, feat_dim), nn.LeakyReLU()] + \
                 [nn.Linear(feat_dim, feat_dim), nn.LeakyReLU()] * (num_layer-1) + \
                 [nn.Linear(feat_dim, self.offset*self.mlp_dim)]
        self.opacity_shift = -2.1792
        self.voxel_size = self.scene_size/self.feat_vol_reso
        self.scaling_shift = np.log(self.voxel_size)
        self.mlp_coarse = nn.Sequential(*layers_coarse).cuda()
        self.offset_act = lambda x: torch.tanh(x)
        self.pos_act = lambda x: x.clamp(-0.5, 0.5)
        self.scale_act = lambda x: torch.exp(x)
        self.opacity_act = lambda x: torch.sigmoid(x)
        # self.opacity_act = lambda x: 0.5 * torch.tanh(x) + 0.5
        self.rot_act = lambda x: F.normalize(x, dim=-1)
        if self.view_color:
            self.rgb_act = lambda x: x.reshape(x.shape[0],x.shape[1],-1,3)
        else:
            self.rgb_act = lambda x: 0.5 * torch.tanh(x) + 0.5 # NOTE: may use sigmoid if train again
        self.init(self.mlp_coarse)
        self.gs_render = Renderer(sh_degree=cfg.sh_degree,view_color=self.view_color)
    def init(self, layers):
        # MLP initialization as in mipnerf360
        init_method = "xavier"
        if init_method:
            for layer in layers:
                if not isinstance(layer, nn.Linear):
                    continue 
                if init_method == "kaiming_uniform":
                    torch.nn.init.kaiming_uniform_(layer.weight.data)
                elif init_method == "xavier":
                    torch.nn.init.xavier_uniform_(layer.weight.data)
                torch.nn.init.zeros_(layer.bias.data)
                
    def build_dense_grid(self, reso):
        array = torch.arange(reso, device=self.device)
        grid = torch.stack(torch.meshgrid(array, array, array, indexing='ij'),dim=-1)
        grid = (grid + 0.5) / reso * 2 -1
        return grid.reshape(reso,reso,reso,3)*self.scene_size
    ###   
    def projection(self,grid, w2cs, ixts):
        # temp = w2cs[:,:3,:3].permute(0,2,1)
        points = grid.reshape(1,-1,3) @ w2cs[:,:3,:3].permute(0,2,1) + w2cs[:,:3,3][:,None]
        points = points @ ixts.permute(0,2,1)
        points_xy = points[...,:2]/points[...,-1:]
        return points_xy, points[...,-1:]
    ###
    def ray_to_plucker(self, rays):
        origin, direction = rays[...,:3], rays[...,3:6]
        # Normalize the direction vector to ensure it's a unit vector
        direction = F.normalize(direction, p=2.0, dim=-1)
        
        # Calculate the moment vector (M = O x D)
        moment = torch.cross(origin, direction, dim=-1)
        
        # Plucker coordinates are L (direction) and M (moment)
        return torch.cat((direction, moment),dim=-1)
    #### 
    def build_feat_vol(self, src_inps, img_feats, n_views_sel, batch,is_img):

        b,c,h,w = src_inps.shape
        src_ixts = torch.eye(3)
        # data_ixts = batch["ixt"]
        src_ixts[:2,:] = batch["ixt"][:1,:,:]
        src_ixts = src_ixts.unsqueeze(0).repeat(b,1,1).to(self.device)
        src_w2cs = batch['w2c'][:,:self.input_views,:,:].squeeze(0).to(self.device).reshape(-1,4,4)
        

        img_wh = torch.tensor([w,h], device=self.device)
        point_img,_ = self.projection(self.volume_grid, src_w2cs, src_ixts) 
        point_img = (point_img+ 0.5)/img_wh*2 - 1.0
        
        # viewing direction
        rays = batch['rays_down'][:,:self.input_views,:,:,:].to(self.device)
        feats_dir = self.ray_to_plucker(rays).reshape(-1,*rays.shape[2:])
        feats_dir = torch.cat((rsh_cart_3(feats_dir[...,:3]),rsh_cart_3(feats_dir[...,3:6])),dim=-1)

        # query features
        img_feats =  torch.einsum('bchw->bhwc',img_feats)
        if is_img:
            img_feats = self.dir_norm_img(img_feats, feats_dir)
        else:
            img_feats = self.dir_norm_nor(img_feats, feats_dir)
            # img_feats = self.dir_norm_img(img_feats, feats_dir)
        img_feats = torch.einsum('bhwc->bchw',img_feats)

        n_channel = img_feats.shape[1]
        feats_vol = F.grid_sample(img_feats.float(), point_img.unsqueeze(1), align_corners=False).to(img_feats)

        # img features
        feats_vol = feats_vol.view(-1,n_views_sel,n_channel,self.feat_vol_reso,self.feat_vol_reso,self.feat_vol_reso)
        return feats_vol
        
    def forward(self, batch,is_gui=False):
        B,N,C,H,W = batch["input_images"].shape
        _inps =batch["input_images"].reshape(B*N,C,H,W).to(self.device)
        _inps_normal =batch["input_normals"].reshape(B*N,C,H,W).to(self.device)
        # image encoder
        img_feats = torch.einsum('blc->bcl', self.img_encoder(_inps))
        token_size = int(np.sqrt(H*W/img_feats.shape[-1]))
        img_feats = img_feats.reshape(*img_feats.shape[:2],H//token_size,W//token_size)
        #normal encoder
        nor_feats = torch.einsum('blc->bcl', self.img_encoder(_inps_normal))
        token_size = int(np.sqrt(H*W/nor_feats.shape[-1]))
        nor_feats = nor_feats.reshape(*nor_feats.shape[:2],H//token_size,W//token_size)
        # build 3D volume
        img_feat_vol = self.build_feat_vol(_inps, img_feats, N, batch,is_img=True)
        nor_feat_vol = self.build_feat_vol(_inps_normal, nor_feats, N, batch,is_img=False)
        # view embeddings
        if self.view_embed_e:
            img_feat_vol = torch.cat((img_feat_vol, self.view_embed[:,:self.input_views].expand(B,-1,-1,self.feat_vol_reso,self.feat_vol_reso,self.feat_vol_reso)),dim=2)
            nor_feat_vol = torch.cat((nor_feat_vol, self.view_embed[:,self.input_views:].expand(B,-1,-1,self.feat_vol_reso,self.feat_vol_reso,self.feat_vol_reso)),dim=2)
        #
        img_feat_vol = img_feat_vol.mean(dim=1)
        nor_feat_vol = nor_feat_vol.mean(dim=1)
        GF_feats = self.GF_fusion(img_feat_vol,nor_feat_vol)
        parameters = self.mlp_coarse(GF_feats).float()
        parameters = parameters.view(parameters.shape[0],-1,self.mlp_dim)
        gs_offsets, gs_opacity,gs_scales,gs_rots,gs_colors = torch.split(
            parameters, 
            [3, 1, 2, 4, self.mlp_dim-10],
            dim=-1
            )
        gs_opacity = gs_opacity+self.opacity_shift
        gs_scales = gs_scales+self.scaling_shift
        gs_offsets = self.offset_act(gs_offsets)
        gs_position = self.volume_grid.detach().view(1,-1,3).repeat(B,self.offset,1)
        if self.move:
            gs_position = self.pos_act(gs_position+gs_offsets*self.scene_size)
        else:
            gs_position = self.pos_act(gs_position+gs_offsets*(self.scene_size/self.feat_vol_reso))
        
        # gs_position = self.pos_act(gs_position+gs_offsets*self.scene_size)
        gs_opacity = self.opacity_act(gs_opacity)
        # gs_convs = self.mlp_cov(feat_vol).view(B,-1,7)
        gs_scales = self.scale_act(gs_scales)
        gs_rots = self.rot_act(gs_rots)
        gs_colors = self.rgb_act(gs_colors)
        
        if is_gui:
            return gs_position,gs_opacity,gs_scales,gs_rots,gs_colors
        else:
            out = self.gs_render.render(batch,gs_position,gs_opacity,gs_scales,gs_rots,gs_colors)
            return out
    
    def save_ply(self, gs_position,gs_opacity,gs_scales,gs_rots,gs_colors, path):
        # gaussians: [B, N, 14]
        # compatible: save pre-activated gaussians as in the original paper
        _,N,_ = gs_position.shape
        means3D = gs_position
        opacity = gs_opacity
        scales = gs_scales
        rotations = gs_rots
        shs = gs_colors # [N, 1, 3]
        xyzs = means3D.detach().cpu().numpy().squeeze()
        f_dc = shs.detach().cpu().numpy().squeeze()
        opacities = opacity.detach().cpu().numpy().squeeze()
        opacities = np.expand_dims(opacities,axis=1)
        scales = scales.detach().cpu().numpy().squeeze()
        rotations = rotations.detach().cpu().numpy().squeeze()
        vertex_data = np.empty(N, dtype=[('x', 'f4'), ('y', 'f4'), ('z', 'f4'),
                                         ('opa', 'f4'),
                                         ('x_s', 'f4'), ('y_s', 'f4'),
                                         ('r1', 'f4'), ('r2', 'f4'), ('r3', 'f4'), ('r4', 'f4'),
                                         ('shs', 'f4', (4, 3))])
        vertex_data['x'], vertex_data['y'], vertex_data['z'] = xyzs[:, 0], xyzs[:, 1], xyzs[:, 2]
        vertex_data['opa'] = opacities.flatten()
        vertex_data['x_s'], vertex_data['y_s'] = scales[:, 0], scales[:, 1]
        vertex_data['r1'], vertex_data['r2'], vertex_data['r3'], vertex_data['r4'] = rotations[:, 0], rotations[:, 1], rotations[:, 2], rotations[:, 3]
        vertex_data['shs'] = f_dc

        # 创建PlyElement
        vertex_element = PlyElement.describe(vertex_data, 'vertex')

        # 创建PlyData并写入文件
        ply_data = PlyData([vertex_element])
        if not os.path.exists(path):
            os.makedirs(path)
        ply_data.write(os.path.join(path,"gs.ply"))
    
    def load_ply(self, path):


        # 读取PLY文件
        ply_data = PlyData.read(path)

        # 提取数据
        vertex_data = ply_data['vertex']

        # 重构tensor
        gs_position = torch.tensor(np.column_stack((vertex_data['x'], vertex_data['y'], vertex_data['z']))).unsqueeze(0).cuda()
        _,N,_ = gs_position.shape
        gs_opacity = torch.tensor(vertex_data['opa']).unsqueeze(0).unsqueeze(-1).cuda()
        gs_scales = torch.tensor(np.column_stack((vertex_data['x_s'], vertex_data['y_s']))).unsqueeze(0).cuda()
        gs_rots = torch.tensor(np.column_stack((vertex_data['r1'], vertex_data['r2'], vertex_data['r3'], vertex_data['r4']))).unsqueeze(0).cuda()
        gs_colors = torch.tensor(np.array(list(vertex_data['shs']))).unsqueeze(0).reshape(1,N,4,3).cuda()

        return gs_position,gs_opacity,gs_scales,gs_rots,gs_colors

        
class ModLN(L.LightningModule):
    """
    Modulation with adaLN.
    
    References:
    DiT: https://github.com/facebookresearch/DiT/blob/main/models.py#L101
    """
    def __init__(self, inner_dim: int, mod_dim: int, eps: float):
        super().__init__()
        self.norm = nn.LayerNorm(inner_dim, eps=eps)
        self.mlp = nn.Sequential(
            nn.SiLU(),
            nn.Linear(mod_dim, inner_dim * 2),
            # nn.LayerNorm(inner_dim*2, eps=eps)
        )

    @staticmethod
    def modulate(x, shift, scale):
        # x: [N, L, D]
        # shift, scale: [N, D]
        return x * (1 + scale) + shift

    def forward(self, x, cond):
        shift, scale = self.mlp(cond).chunk(2, dim=-1)  # [N, D]
        return self.modulate(self.norm(x), shift, scale)  # [N, L, D]