train_data: ""
val_data: ""
test_data: "./examples"
camera_json: ""
outdir: "./result"
resume: "./model/final_model.safetensors" # or resume: "./mid/final_model.safetensors"
batch_size: 4
num_workers: 4
lambda_lpips: 0.5
lambda_dist: 0.1
lambda_normal: 0.5
lambda_reg: 0
lambda_depth: 1.0
lr : 1e-5
T_max: 32
total_epoch: 200
save_iter: 100000
imgs_iter: 100
sh_degree: 1
view: 6
move_range: False
view_color: True
### test
save_gs: False
save_imgs: "./output"
output_size: 256
###
model:
    encoder_backbone: 'vit_base_patch16_224.dino' # ['vit_small_patch16_224.dino','vit_base_patch16_224.dino']
    scene_size: 0.5
    per_voxel_gs: 1    # primitives per-voxel
    num_layers: 12
    num_heads: 16
    view_embed_dim: 32
    embedding_dim: 256
    vol_feat_reso: 32
    vol_embedding_reso: 32
    vol_embedding_out_dim: 80
